gen:
	protoc --go_out=../../gen/go --go_opt=paths=source_relative --go-grpc_out=../../gen/go --go-grpc_opt=paths=source_relative next.proto

    # git push origin v0.0.1 ||| git tag v0.0.1
    # go get <repo-name>@latest | go get <repo-name>@v0.0.1